# Dataset Metadata Extraction Tool Configuration v1.1.3
# Choose between 'openai' or 'local' LLM provider

llm:
  # Provider: 'openai' or 'local'
  provider: "local"  # Change to "openai" to use OpenAI API

  # OpenAI Configuration
  openai:
    api_key: "your-openai-api-key-here"  # Or use environment variable OPENAI_API_KEY
    model: "gpt-4"  # Options: gpt-3.5-turbo, gpt-4, gpt-4-turbo
    max_tokens: 300
    temperature: 0.7
    timeout: 30  # seconds

  # Local LLM Configuration
  local:
    api_url: "http://localhost:8000/generate"  # Update with your local server URL
    max_tokens: 300
    temperature: 0.7
    timeout: 30  # seconds
    headers:
      Content-Type: "application/json"
      ngrok-skip-browser-warning: "true"  # For ngrok tunnels

# Application Settings
app:
  debug: true
  max_file_size_mb: 20  # Maximum file upload size
  session_cleanup_hours: 1

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  show_prompts: true  # Set to false to hide detailed prompt logging