version: '3.8'

services:
  # Main application service
  metadata-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-metadata-tool
    ports:
      - "5000:5000"
    environment:
      # Flask configuration
      - FLASK_ENV=production
      - FLASK_DEBUG=false

      # LLM Configuration (override via .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}

      # Supabase Configuration (override via .env file)
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_KEY=${SUPABASE_KEY:-}

      # Application settings
      - PYTHONUNBUFFERED=1
      - TZ=UTC

    volumes:
      # Mount configuration file
      - ./config.yaml:/app/config.yaml:ro

      # Mount uploads and temp directories for persistence
      - uploads-data:/app/uploads
      - temp-data:/app/temp
      - backups-data:/app/backups

      # Optional: Mount logs directory
      - logs-data:/app/logs

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  metadata-tool-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-metadata-tool-dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_KEY=${SUPABASE_KEY:-}
      - PYTHONUNBUFFERED=1

    volumes:
      # Mount source code for development
      - .:/app
      - uploads-data:/app/uploads
      - temp-data:/app/temp
      - logs-data:/app/logs

    restart: unless-stopped
    profiles:
      - dev

# Named volumes for data persistence
volumes:
  uploads-data:
    driver: local
  temp-data:
    driver: local
  backups-data:
    driver: local
  logs-data:
    driver: local

# Networks (optional)
networks:
  default:
    name: metadata-tool-network